name: Unit converter

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '>=19.7'
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies
      run: npm ci

    - name: Transpile TypeScript
      run: npm run build

    - name: Publish to NPM
      run: npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
