name: '@chrisjohdev/unit_converter'
on:
  push:
    branches:
      - master
jobs:
  release:
    name: '@chrisjohdev/unit_converter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "19.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
