name: Unit converter

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  transpile-typescript:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '>=19.7'

    - name: Install Dependencies
      run: npm ci

    - name: Transpile TypeScript
      run: npm run build
    
    # Added for debugging
    - name: List directories after build
      run: ls -al
  
  copy-files:
    needs: transpile-typescript
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Added for debugging
    - name: List directories before copy
      run: ls -al

    - name: Copy files to dist
      run: cp -v package.json README.md dist/

    - name: Upload dist directory
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
    

    # Added for debugging
    - name: List content of dist/
      run: ls -al dist/


  publish-npm:
    needs: copy-files
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '>=19.7'
        registry-url: 'https://registry.npmjs.org'

    - name: Download dist directory
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist/
      

    - name: Publish to NPM
      run: npm publish dist/  --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
